# in 'init' we can have bash-code that is executed during the pre-build.
# We also run 'mvn test' without actually running the tests to ensure all dependencies are fetched.
# in 'command' we have bash-code that is executen in the Gitpod Terminal View when the user opens a workspace.
tasks:
  - before: |
      cd workshop
    init: |
      mvn clean install -DskipTests=true
      clear
      echo 'Ready to start!'
    command: |
      gp open src/test/java/com/saucedemo/exercises/E2ETests.java

vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - redhat.vscode-xml
